# Generated by Django 5.2.6 on 2025-09-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
